apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: weatherforecast-fsharp
  namespace: dotnet
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: weatherforecast-fsharp
spec:
  source:
    git:
      url: https://github.com/fabianbrash/weatherforecast-fsharp.git
      ref:
        branch: main
